# docker-compose.yaml
  
version: '3.8'
services:

    jenkins:
      image: jenkins/jenkins:lts
      restart: unless-stopped
      container_name: jenkins
      privileged: true
      user: root
      ports:
       - 8080:8080
       - 50000:50000
      volumes:
       - /data/jenkins:/var/jenkins_home
       - /var/run/docker.sock:/var/run/docker.sock
